CREATE DATABASE IF NOT EXISTS exchange;
USE exchange;

CREATE TABLE IF NOT EXISTS users (
    id varchar(36) PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stocks (
    stock_id MEDIUMINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    symbol VARCHAR(10) UNIQUE NOT NULL,
    name VARCHAR(50) NOT NULL,
    current_price DECIMAL(10, 2) NOT NULL,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE if NOT EXISTS stock_price_history (
    history_id INT PRIMARY KEY AUTO_INCREMENT,
    stock_id MEDIUMINT UNSIGNED NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    recorded_at BIGINT NOT NULL,
    FOREIGN KEY (stock_id) REFERENCES Stocks(stock_id),
    INDEX (recorded_at)
);