version: '3.9'
services:
  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
  backend:
    container_name: backend
    build:
      context: .
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - .:/app/src
    env_file:
      - .env
    environment:
      - INTERNAL_NETWORK=true
    depends_on:
      kafka:
        condition: service_started
      db: 
        condition: service_healthy 
      redis-ws:
        condition: service_started
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=exchange
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 7s
      timeout: 20s
      retries: 5
  redis-ws:
    container_name: redis-ws
    image: redis:latest
    ports:
      - 6379:6379