version: '3.9'
services:
  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
  backend:
    container_name: backend
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - .:/app/src
    env_file:
      - .env
    environment:
      - INTERNAL_NETWORK=true
    depends_on:
      - kafka